### ISSUE TITLE
Resolve Behat test issues on Travis CI

### ISSUE THREAD

**Issue by arithmetric** [phase2/grunt-drupal-tasks#88]
Behat tests fail on Travis CI with the following error:

```
Fatal error: Cannot inherit previously-inherited constant BEFORE in /home/travis/build/phase2/grunt-drupal-tasks/test/working_copy/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Hook/Scope/BeforeUserCreateScope.php on line 13
```

For example, see: https://travis-ci.org/phase2/grunt-drupal-tasks/builds/45110439

The tests pass on a local env with similar configuration (PHP 5.4.30).

**Comment by jhedstrom** [comment]
Tests are passing locally for me using php 5.5.19.

Some links:

* https://stackoverflow.com/questions/16097973/marker-constant-override-symfony2-error
* https://github.com/swiftmailer/swiftmailer/issues/477
* https://bugs.php.net/bug.php?id=59101

the common theme seems to be that this is APC related (but the linked bug indicates it was fixed in 2010).

**Comment by arithmetric** [comment]
Thanks for looking into this @jhedstrom.

I ran a few tests on Travis to follow up on this:

- I added the PHP 5.5 env, but still saw the PHP error: https://travis-ci.org/phase2/grunt-drupal-tasks/builds/47274633

- I ran a test to get the output from `php -i` and see that the APC extension is not enabled: https://travis-ci.org/phase2/grunt-drupal-tasks/builds/47276583

- This includes the output from `pecl list` and `ls -lR ~/.phpenv`: https://travis-ci.org/phase2/grunt-drupal-tasks/builds/47277906

**Comment by smerrill** [comment]
It looks like 5.4 and 5.5 use opcache. Sadly, neither opcache nor XDebug appear to be the issue - I've disabled both in that branch and our tests still fail.

**Comment by smerrill** [comment]
It also fails in a container-based build with opcache and XDebug removed. (I had to change netstat -an to a curl test.)

https://travis-ci.org/phase2/grunt-drupal-tasks/jobs/50783206

**Comment by smerrill** [comment]
I bet this has to do with ZTS. No major distro ships packages with ZTS on, but Travis does for some reason.

https://github.com/travis-ci/travis-ci/issues/985

**Comment by arithmetric** [comment]
This error is no longer present on Travis CI tests. :smiley:

The first successful pass seems to have happened here: https://travis-ci.org/phase2/grunt-drupal-tasks/jobs/67241663

So, this might have been fixed by #178.

**Comment by jhedstrom** [comment]
:+1:

**Comment by smerrill** [comment]
:100:
